services:
  - type: web
    name: ghost-cms-final
    runtime: docker
    region: oregon
    plan: starter # Платный план для постоянного хранения
    
    envVars:
      - key: NODE_ENV
        value: production
      
      - key: url
        value: https://ghost-cms-final.onrender.com
      
      - key: database__client
        value: sqlite3
      
      - key: database__connection__filename
        value: /var/lib/ghost/content/data/ghost.db
      
      # Email configuration (Zoho SMTP)
      - key: mail__transport
        value: SMTP
      
      - key: mail__options__host
        value: smtp.zoho.com
      
      - key: mail__options__port
        value: 587
      
      - key: mail__options__secure
        value: false
      
      - key: mail__options__auth__user
        value: noreply@dentalprice.ai
      
      - key: mail__options__auth__pass
        value: yFBJKnVS8Arw
      
      - key: mail__from
        value: DentalPrice AI <noreply@dentalprice.ai>
    
    disk:
      name: ghost-storage
      mountPath: /var/lib/ghost/content
      sizeGB: 1
    
    autoDeploy: true