services:
  - type: web
    name: ghost-cms-final
    runtime: docker
    region: oregon
    plan: starter # Платный план для постоянного хранения
    
    envVars:
      - key: NODE_ENV
        value: production
      
      - key: url
        value: https://ghost-cms-final.onrender.com
      
      - key: database__client
        value: sqlite3
      
      - key: database__connection__filename
        value: /var/lib/ghost/content/data/ghost.db
    
    disk:
      name: ghost-storage
      mountPath: /var/lib/ghost/content
      sizeGB: 1
    
    autoDeploy: true