services:
  - type: web
    name: ghost-cms-simple
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    region: oregon
    plan: starter # $7/месяц для постоянного хранения
    branch: main
    
    envVars:
      # Основные настройки
      - key: NODE_ENV
        value: production
      
      - key: url
        value: https://ghost-cms-simple.onrender.com
      
      # База данных
      - key: database__client
        value: sqlite3
      
      - key: database__connection__filename
        value: /var/lib/ghost/content/data/ghost.db
      
      # Отключаем email верификацию
      - key: auth__type
        value: password
      
      - key: auth__method
        value: password
      
      - key: labs__emailVerification
        value: false
      
      - key: members__emailVerification
        value: false
      
      - key: admin__emailVerification
        value: false
    
    # Постоянное хранилище для SQLite
    disk:
      name: ghost-data
      mountPath: /var/lib/ghost/content
      sizeGB: 1
    
    # Автодеплой
    autoDeploy: true
    
    # Health check
    healthCheckPath: /ghost/api/admin/site/