services:
  - type: web
    name: dentalprice-blog
    runtime: docker
    region: oregon
    plan: starter # Платный план для постоянного хранения
    
    envVars:
      - key: NODE_ENV
        value: production
      
      - key: url
        value: https://blog.dentalprice.ai
      
      - key: database__client
        value: sqlite3
      
      - key: database__connection__filename
        value: /var/lib/ghost/content/data/ghost.db
      
      # Email configuration (Zoho SMTP для админки)
      - key: mail__transport
        value: SMTP
      
      - key: mail__options__host
        value: smtp.zoho.com
      
      - key: mail__options__port
        value: 587
      
      - key: mail__options__secure
        value: false
      
      - key: mail__options__auth__user
        value: noreply@dentalprice.ai
      
      - key: mail__options__auth__pass
        value: yFBJKnVS8Arw
      
      - key: mail__from
        value: noreply@dentalprice.ai
      
      # Members email configuration (SendGrid для подписчиков)
      - key: members__email__transport
        value: SMTP
      
      - key: members__email__options__host
        value: smtp.sendgrid.net
      
      - key: members__email__options__port
        value: 587
      
      - key: members__email__options__auth__user
        value: apikey
      
      - key: members__email__options__auth__pass
        sync: false  # Add SendGrid API key manually in Render Dashboard
      
      - key: members__emailFromAddress
        value: noreply@dentalprice.ai
      
      - key: members__email__from
        value: noreply@dentalprice.ai
    
    disk:
      name: ghost-storage
      mountPath: /var/lib/ghost/content
      sizeGB: 1
    
    customDomains:
      - name: blog.dentalprice.ai
    
    autoDeploy: true