services:
  # Ghost CMS для Multi-Site архитектуры
  - type: web
    name: ghost-multisite-cms
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    region: oregon
    plan: free # Бесплатный план для начала
    branch: main
    
    # Render не поддерживает persistent disk для Docker, 
    # поэтому используем внешнюю БД или SQLite в памяти
    
    envVars:
      # Основные настройки
      - key: NODE_ENV
        value: production
      
      - key: url
        # Временно используем домен Render, потом поменяете на свой
        value: https://ghost-multisite-cms.onrender.com
      
      # База данных - используем SQLite для начала
      - key: database__client
        value: sqlite3
      
      - key: database__connection__filename
        value: /var/lib/ghost/content/data/ghost.db
      
      # Email настройки (опционально)
      - key: mail__transport
        value: SMTP
      
      - key: mail__from
        value: noreply@dentalprice.ai
      
      - key: mail__options__service
        value: Mailgun
      
      - key: mail__options__auth__user
        sync: false # Добавьте вручную в Render Dashboard
      
      - key: mail__options__auth__pass
        sync: false # Добавьте вручную в Render Dashboard
      
      # S3 для хранения изображений (опционально - раскомментируйте если нужно)
      # - key: storage__active
      #   value: s3
      # - key: storage__s3__accessKeyId
      #   sync: false
      # - key: storage__s3__secretAccessKey
      #   sync: false
      # - key: storage__s3__bucket
      #   value: dentalprice-blog-images
      # - key: storage__s3__region
      #   value: us-west-2
      
      # Portal настройки
      - key: portal__name
        value: Multi-Site Content Hub
      
      - key: portal__button
        value: true
      
    
    # Автодеплой при push
    autoDeploy: true
    
    # Health check
    healthCheckPath: /ghost/api/admin/site/
    
    # Custom domains - раскомментируйте когда будете готовы подключить свой домен
    # customDomains:
    #   - blog.dentalprice.ai

# SQLite используется временно для упрощения деплоя
# Позже можно переключиться на PostgreSQL когда Ghost заработает

# Для PostgreSQL раскомментируйте:
# databases:
#   - name: ghost-multisite-db
#     databaseName: ghost_production
#     user: ghost_user
#     region: oregon
#     plan: free